export const CATEGORIES = [
  'Accounting / Finance',
  'Admin / Office / Clerical',
  'Agriculture / Veterinary',
  'Arts / Media / Design',
  'Call Center / BPO',
  'Domestic / Caretaker',
  'Education / Schools',
  'Engineering / Architecture',
  'Food / Restaurant',
  'Foreign Language',
  'Government / Non-profit',
  'Health / Medical / Science',
  'Hotel / Spa / Salon',
  'HR / Recruitment / Training',
  'IT / Computers',
  'Legal / Documentation',
  'Logistics / Warehousing',
  'Maritime / Seabased',
  'Production / Manufacturing',
  'Purchasing / Buyer',
  'Sales / Marketing / Retail',
  'Skilled Work / Technical',
  'Others',
];
